version: '3.8'

services:
  database:
    image: postgres:13.3-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cafe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      apps-net: { aliases: [ database.apps-net ] }

  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: cafeapp:1.0
    ports:
      - 8080:8080
    networks:
      apps-net: { aliases: [ app.apps-net ] }

networks:
  apps-net:
    driver: bridge

