spring:
  liquibase:
    change-log: classpath:/db/changelog/changes/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://database:5432/cafe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
